name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List file
        run: |
          pwd
          ls -l
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: List file after checkout
        run: |
          pwd
          ls -l
      - name: Simple JS Action
        id: simple-js-action
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: "DJ JJ"
      - name: Log Greeting Time
        run: echo  "${{steps.simple-js-action.outputs.time}}"
